### ISSUE TITLE
can not create shop

### ISSUE THREAD

**Issue by Tokisaki** [renzuzu/renzu_shops#10]
Hello,
    when I try to creat a shop its dosn't work and serverlog show that
SCRIPT ERROR: @renzu_shops/server/main.lua:274: attempt to index a nil value (field 'shared')

**Comment by renzuzu** [comment]
fix thanks for noticing.
https://github.com/renzuzu/renzu_shops/commit/034045d578ff313e420c47c6eaf27ea573b6abdd
