### ISSUE TITLE
literally everyone can see my owned business and access my funds or either make there self an employee

### ISSUE THREAD

**Issue by ljdunn00** [renzuzu/renzu_shops#101]

**Comment by renzuzu** [comment]
Not actionable without information

**Comment by ljdunn00** [comment]
wym bro they can literally come in and take and spemnd my money

**Comment by renzuzu** [comment]
well thats weird, it should not happen.
i will verify this, probably something with new job function checking..

**Comment by renzuzu** [comment]
it seems this does not exist on me.
only the owner can see marker or targets of My Store function


can you tell me your framework?

**Comment by ljdunn00** [comment]
esx t

**Comment by ljdunn00** [comment]
si i deleted my owner ship and rebought it made new player and i cant view it so i think maybe it good will have other players test and btw anything i shoul delete using renzu_shops because i like the vehicle lua u got and no longer wanna use esx vehicle shop

**Comment by ljdunn00** [comment]
naw im saying other players cant view the store nomore i think it was my db i deleted my ownershhip seems fine now

**Comment by ljdunn00** [comment]
well how do i cross out the blimps for the shop i had Cookies = {
        name = 'ZaZa Cookies',
    --    blip = {
        --    id = 403, colour = 69, scale = 0.8
        }, inventory = {
            { name = 'banana_kush_joint', price = 45 },
            { name = 'lighter', price = 2 },
            { name = 'gelato_runtz', price = 70 },
            { name = 'blue_dream_joint', price = 60 }
        }, locations = {
            vec3(-933.44, -1178.32, 5.0)
        }, targets = {

        }
    },
which doesnt work how does it work for ur script ?

**Comment by renzuzu** [comment]
removing blips is supported aafaik.

![image](https://user-images.githubusercontent.com/82306584/229470554-835b3792-bde4-43d1-8589-674038fe09d9.png)


try removing it in defaultshops, ownedshop/cookie.lua

**Comment by ljdunn00** [comment]
YO I CANT ADD SHOPS NOW ?

**Comment by renzuzu** [comment]
you can, your just adding it in a wrong way..

when adding non businesss shops, add it on defaultshops.lua

if adding business shop

you need to add new file ex. Cookies.lua in /ownedshops/
and add that lua to /ownedshops/init.lua

add coordinates to /defaultshops by adding a new table line.

or use the shop creator with target disable.

**Comment by ljdunn00** [comment]
shop creator where dats at

**Comment by ljdunn00** [comment]
and i been adding shop just the blimp sht and ohhh wen i buy a car itdoesnt let me turn radio off after

**Comment by ljdunn00** [comment]
error for false payment method ? like im getting no suck register stash in qb core im not even using qb bro dis all happening with this new updatesht been tripping bro i been adding shops in dis script for like 2months nvr had a problem

**Comment by ljdunn00** [comment]
ight its saying false payment bro wassup wit yall script bra sht da older version is better had no issues i update  dis shitty ass sht ass hella errors qb sht im not even on qbcore bra tf fucking up my server bra

**Comment by ljdunn00** [comment]
/storeadmin or /stores no command boutta delete dis sht bra ion kno y u upated dis sht

**Comment by ljdunn00** [comment]
ion kno y tf i downloaded the latest update anyway dat was just dumb asf by me ik better

**Comment by ljdunn00** [comment]
false payment method lmfao smh bra shitty asf

**Comment by ljdunn00** [comment]
that pops up nothing and also wtf up wit da script y the payments say false it annoying cause i do as u say sht still dnt be woorking everytim i do wat u say a new error pop up what is the false payment sht cause wen i was just making shops i nbr put them in owned just a new shop bro and i was able to buy sht and all i did it as u said i kant buy nun bro ik how to add shops been doin it 2months

**Comment by ljdunn00** [comment]
thank you bro i got it my bad was tlkn to much wasnt paying attention my bad everything good now

**Comment by ljdunn00** [comment]
payment method false ?
