### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by Peez500** [renzuzu/renzu_shops#102]
![Screenshot 2023-04-01 162508](https://user-images.githubusercontent.com/121979322/229326001-df1b99af-d154-429d-b8fb-e05d8d614756.png)

**Comment by StableBarcodeDev** [comment]
got the same error.  I also got this 
![Screenshot_41](https://user-images.githubusercontent.com/92280829/229331235-6e68d4fc-c3e0-42ff-bc94-2c5864868de8.png)
![Screenshot_39](https://user-images.githubusercontent.com/92280829/229331260-99d66500-6126-4ae1-bce6-7ca6efa422b4.png)

**Comment by renzuzu** [comment]
can you use the latest update from main branch? i cannot guess until i see the same error lines that does match the main branch.

**Comment by Peez500** [comment]
i replaced it wit the most recent update all i do is save my storeitems.lua and defaultstores.lua

**Comment by renzuzu** [comment]
you mean the post of your picture is using the latest update?
im talking about main branch
https://github.com/renzuzu/renzu_shops/archive/refs/heads/main.zip

not the released download

**Comment by Peez500** [comment]
oh ok

**Comment by Peez500** [comment]
im gon let u know

**Comment by renzuzu** [comment]
yeah, if error is thrown, show me and tell me which part of it . ex. when opening shop etc.

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229342588-2876860b-1a5d-4da9-b887-6abb586342bd.png)

this wat i got

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229342670-65554c14-2c21-4c41-8125-c8a5fbfcc693.png)

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229343705-4506d6ac-93d3-422f-866d-54d373606e7b.png)

**Comment by renzuzu** [comment]
1st pic is error from config. syntax error probably,

3rd pic is when you restart the server this is known issue right now, but does not break the resource. i will probably remove that since i feel it does not need anymore

**Comment by Peez500** [comment]
and know im gettin these 
![image](https://user-images.githubusercontent.com/121979322/229373420-e1a70099-8142-492f-8069-c659acfe569b.png)

**Comment by Peez500** [comment]
i need these errors fixes asap i got ah server 
![image](https://user-images.githubusercontent.com/121979322/229385839-3d1d8952-617b-4491-bf0a-d9848328a703.png)

**Comment by renzuzu** [comment]
all your errors is connected to each others.

you have syntax error in your config.

try installing fresh including default config.
the error is from ownedshops/*.lua

**Comment by Peez500** [comment]
do u think it because in my ox_inventory every place i had a store on this script i had it in ox and i was the ox markers on top of the stores so it can open it without the third eye ion know if that was the problem

**Comment by Peez500** [comment]
and even wit the fresh it still has errors

**Comment by renzuzu** [comment]
i refactored the resource to show minimal errors only instead of printing everything on client/server console.

so we can debug your issue.

you should show what error after you install the new one.

**Comment by Peez500** [comment]
ok im finna see

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229655345-2c254773-d50f-47dc-ac15-d11ddf9509ab.png)

**Comment by Peez500** [comment]
how do u change the markers 
![image](https://user-images.githubusercontent.com/121979322/229655523-9fe2478e-b239-4f7a-a4ef-06701922c0a9.png)

**Comment by Peez500** [comment]
and this error popped up, 
![image](https://user-images.githubusercontent.com/121979322/229655756-61c76e75-95c5-4bcc-9dd5-918f36446e1f.png)

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/229690035-b028331e-95e9-4749-bb53-c1cba9eda677.png)

you have some error from config.

**Comment by Peez500** [comment]
i don't know what it is want me to send u my config so u can see ??

**Comment by Peez500** [comment]
i but the newest version and im starting fresh it seem ta be working coo right now but how do i change the marker

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229798234-25afe21a-93cd-4ca1-b896-a37a0a1e7b40.png)
i be gettin this error but the stores be working

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229837725-8e31ff6a-eb3f-4ccc-95b1-ad787ffc989b.png)
all my newly added default payment method don't work?

**Comment by Peez500** [comment]
the other stores work tho

**Comment by renzuzu** [comment]
this resource requries 
https://github.com/renzuzu/qb-inventory

if using qbcore or use ox_inventory in qbcore

**Comment by Peez500** [comment]
i have same problem as the dude with the default shops it doesn't let me pay at me blackmarket or any new shops i got

**Comment by renzuzu** [comment]
there is a fix with payment method which is reported a while ago

**Comment by Peez500** [comment]
i seen but i really didn't understand

**Comment by renzuzu** [comment]
just update the client/main.lua

**Comment by Peez500** [comment]
any lines in particular

**Comment by renzuzu** [comment]
see https://github.com/renzuzu/renzu_shops/commit/40c95d6cf7b17627571848feefa01d7ae836874f

**Comment by Peez500** [comment]
im confused im not that good wit code fr
