### ISSUE TITLE
[defaultshops] When i create a new location for a shop

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_shops#106]
When i go to buy something there is not money or bank choose payment in new shops but in old default shops they are working

**Comment by Gameadictive** [comment]
![Captura](https://user-images.githubusercontent.com/65845786/229636895-a77af82c-ffd2-4b8d-ac4b-9bee7ee81cdd.PNG)

**Comment by Gameadictive** [comment]
I see the error im changing the vec to vec3

**Comment by Gameadictive** [comment]
Is not working just with that change. What is happening?

**Comment by Gameadictive** [comment]
![Captura](https://user-images.githubusercontent.com/65845786/229641154-3d221017-282a-4acf-87cb-a25ce2c608ae.PNG)

**Comment by renzuzu** [comment]
probably those new coordinates lines is not registered from ownedshops/General.lua

count the index

**Comment by Gameadictive** [comment]
Thanks is exactly that

**Comment by Peez500** [comment]
w

> Thanks is exactly that

what did u do to fix it got the same problem
