### ISSUE TITLE
false

### ISSUE THREAD

**Issue by raaazeee** [renzuzu/renzu_shops#107]
![image](https://user-images.githubusercontent.com/105653892/229865897-99fa9e1e-2191-4746-a259-d483e973ec7f.png)
naka false yung payment sa youtool

**Comment by ljdunn00** [comment]
sht been trippion since da update den dey dnt let u use older version

**Comment by StableBarcodeDev** [comment]
For me seems that happend with every existing shop

**Comment by ljdunn00** [comment]
i just had it working then it stopped working

**Comment by renzuzu** [comment]
its fixed in latest main branch version
