### ISSUE TITLE
Error when trying to order Items

### ISSUE THREAD

**Issue by jvstin2k** [renzuzu/renzu_shops#121]
When I try to order new Items for any store, it says, that I dont have enough funds in vault, but there defenatly is enough money it it. In the server console comes the following error:

![image](https://user-images.githubusercontent.com/54100497/232244976-32832b46-10e8-4e65-b29c-45d384c02ffd.png)

I just looked up this line of code and its something with the deliverypoints. But I dont know what I did wrong. I also just updated, so its "stock", nothing has been changed on this script. I changed some things before I updated it but it still does not work.

**Comment by renzuzu** [comment]
use latest main branch, this is are fixed
