### ISSUE TITLE
WHEN /STOREADMIN

### ISSUE THREAD

**Issue by Gameadictive** [renzuzu/renzu_shops#124]
When u open to Manage Shops in the List is empty. Why?

**Comment by renzuzu** [comment]
did someone buy the bussiness shop?

**Comment by Gameadictive** [comment]
No

**Comment by Gameadictive** [comment]
As admin i think the manage shops are for see wich shops are there.

**Comment by renzuzu** [comment]
there is no actionable part for admins if the shop is not owned yet.

**Comment by Gameadictive** [comment]
Ok thanks
