### ISSUE TITLE
Need qtarget

### ISSUE THREAD

**Issue by DyroS3** [renzuzu/renzu_shops#13]
so could any possible of qtarget support?

**Comment by renzuzu** [comment]
Ox targets have a compatibility. Does it?

**Comment by dingyu1126** [comment]
yep, u're right, but I don't want have time to change it,so may be could u? if u can ,that's save my time,if not,never mind this

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_shops/commit/05a5d03b3cb9bf71b3aae69988d5e74ba3eab1a5

**Comment by dingyu1126** [comment]
omg,thx man,great job!

**Comment by renzuzu** [comment]
test it first, this is tested only in ox_target using compatibility on their client/compat

i havent test it with actual qtarget.
but it should work.
