### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Raze-Scripts** [renzuzu/renzu_shops#130]
script:renzu_shops] SCRIPT ERROR: @renzu_shops/server/main.lua:1990: attempt to concatenate a nil value (global 'vehicletable')

**Comment by Raze-Scripts** [comment]
any reply tito renz dito sa error?

**Comment by renzuzu** [comment]
try updating all files

**Comment by raaazeee** [comment]
gamit ko na yung 1.2.5 main version pero nalabas padin
