### ISSUE TITLE
issue with add employee and Ondemand Selling

### ISSUE THREAD

**Issue by killA93i** [renzuzu/renzu_shops#16]
Hello, nice script in first time.

When you add a player with ox_target i got a error with coords boolean value from ox_lib. When desactivate ox_target no issue for add employee.
Second problem i have, its when i add employee on the store, the employee have access to the manage store (withdraw/add money etc) but dont have access to Ondemand Selling. Thanks in advance for reply ;)

**Comment by killA93i** [comment]
![image](https://user-images.githubusercontent.com/85191293/201660866-b76d4de0-4c65-4355-9d1b-3b91ebb482f9.png)
I have latest ox_lib / ox_inventory ;)

**Comment by renzuzu** [comment]
i fix the second issue
https://github.com/renzuzu/renzu_shops/commit/a445d2088fb86a439417d1a303d13a015f52c984

the first issue i need more info. is it the other player having error or you the actual owner?

**Comment by killA93i** [comment]
I am a actual owner, but found a fix need just change coords with GetEntityCoords(PlayerPedId()) insane the lib.getNearbyPlayers from the ox lib ;). Thanks to fix the Ondemand Selling. I got another problem dont know how to fix this, but when i buy a shop i need to restart my game before i m owner, like the removezone/addzone from ox_target not work the first time. I need to relog or restart the script. :D

**Comment by killA93i** [comment]
Other problem i got, its when i  transfer the ownership for other player after restart of the server i return owner, dont know why lol

**Comment by renzuzu** [comment]
are you using ox_target?
im acutally having doubts on my zones on target .
show me some error if theres one. i will restest targets later again.

about the ownership transfer. when you transfer you become a employee. can you make sure your a owner or employee?

**Comment by killA93i** [comment]
I print a table of employee and i am employee but after the restart i got back ownership from the store, and yes i using ox_target if i restart the script all are good removezone / addzone working, but if i restart the server and buy a store, need to restart my game or reload the script. If i dont restart my game / reload the script, i can press "Buy the store" but nothing no error. I think this issue appear because the removezone / addzone have some problem when he was not reload just one time, because after reload the script you can buy/sell store and you can see zone has been update and you can manage your store ;)

**Comment by killA93i** [comment]
Renzuzu, maybe this information can help but when you have already bought a shop you can sell it and its instantly refresh not needed to restart script or restart the game ;). Your method for sell store working very well, but not when you buy for the first time

**Comment by renzuzu** [comment]
Hi

Try the latest main brach not beta.

All this issue doea not exist when i tested it with your steps

**Comment by killA93i** [comment]
All other issue related fixed, only one issue again, when i start the server, if i buy a store, need to restart for get a refresh of ox_target for "Buy Store" > "My Store General #1" if i restart the ressource, fixed. When i sell the store i see the reload of ox_target  with the disappearance of the eye tracker on the props and its return some secs after with updated value. For get the issue you need: Just launch your server, buy a store with ox target and check, you can see "Buy Store" and not the new value > "My Store General #1" for example. Thanks renzuzu

**Comment by renzuzu** [comment]
does this issue still exist? on the latest branch
