### ISSUE TITLE
Carry Items

### ISSUE THREAD

**Issue by Consi0** [renzuzu/renzu_shops#19]
In the Script, there is no query, that ask wether we can carry the item or not (ox_inventory)
The second thing I want to mention, can you implemet a locale system, so that I don't have to rewrite the whole client lua after every update? Would be nice!

**Comment by renzuzu** [comment]
in my local copy its have cancarry logic now.
locales are planned already expect it on next update

heres what to expect in next commit
Mysql usage instead of kvp
locales
cancarry item logic

**Comment by Consi0** [comment]
That sounds nice.
