### ISSUE TITLE
attempt to call a nil value (global 'LoadResoursceFile')

### ISSUE THREAD

**Issue by secret-agent313** [renzuzu/renzu_shops#20]
[    c-scripting-core] Creating script environments for renzu_shops
[  script:renzu_shops] Error loading script init.lua in resource renzu_shops: @renzu_shops/init.lua:94: attempt to call a nil value (global 'LoadResoursceFile')
[  script:renzu_shops] stack traceback:
[  script:renzu_shops] 	@renzu_shops/init.lua:94: in function 'request'
[  script:renzu_shops] 	@renzu_shops/init.lua:100: in main chunk
[    c-scripting-core] Failed to load script init.lua.
[ citizen-server-impl] Started resource renzu_shops

Hello, how can I fix this error?

**Comment by renzuzu** [comment]
the print say LoadResoursceFile

its type. did you edit it?

its should be name LoadResourceFile
