### ISSUE TITLE
Remove Job Access

### ISSUE THREAD

**Issue by Consi0** [renzuzu/renzu_shops#23]
1. An Option to Remove the Job Access.
2. When I Sell the Store, the database entry gets removed but i can still open the Menu
3. When i retstart the Script and have bought a store and run into the marker, the database entry is duplicated
4. Sometime when opening the cashier after a Server restart, the menu looks like this: https://gyazo.com/e6d99af78327b431e69bddf5dc593797 and somtimes like this: https://gyazo.com/67e5f8b07fda7ca74941bb57c79c0399 . This only happens after Server Restart and not every time

**Comment by renzuzu** [comment]
the last commit from main branch has a bug from sql.save
it insert multiple rows. thank fully i release a good version 1.0.

the main branch is fix now.

and about the #4 issue i dont know how to reproduce it. as its only happens sometimes. as you said
