### ISSUE TITLE
Vehicle Shop Bug

### ISSUE THREAD

**Issue by DevZiee** [renzuzu/renzu_shops#3]
When you finish purchasing a vehicle, your letter "Q" will be automatically disabled. making it impossible to turn off the vehicle radio.

**Comment by Im-Kayun** [comment]
My letter "Q" works perfectly

**Comment by DevZiee** [comment]
i'll try to figure out

**Comment by Im-Kayun** [comment]
I just tested it on my server, the "Q" key works normally outside of vehicles regardless of whether I use the script or not. When I open the stand, the key no longer works on the vehicles

**Comment by renzuzu** [comment]
The q is something from no clip?

If vehicle is emergency type

You cant bypass els or the siren

Some no clip did that. Assuming its no clip
