### ISSUE TITLE
New version (SQL) groups and rank not working for default shop

### ISSUE THREAD

**Issue by killA93i** [renzuzu/renzu_shops#32]
Hello, i can't create a default shop with renzu shops with groups like groups = 'police' and a set a rank for the item like example of ox_inventory. When i try to print  "groups = var.shop?.groups," he return false. A exemple of my default shop : 

> PoliceArmoury = {
> 		name = 'Armurerie L.S.P.D',
> 		groups = 'police',
> 		blip = {
> 			id = 110, colour = 84, scale = 0.8
> 		}, inventory = {
> 			{ name = 'ammo-9', price = 5, grade = 2 },
> 			{ name = 'ammo-rifle', price = 5, grade = 3 },
> 			{ name = 'tazer_clip', price = 5, },
> 			{ name = 'WEAPON_FLASHLIGHT', price = 200 },
> 			{ name = 'WEAPON_NIGHTSTICK', price = 100 },
> 			{ name = 'WEAPON_GLOCK', price = 500, metadata = { registered = true, serial = 'POL' }, license = 'weapon', grade = 2 },
> 			{ name = 'WEAPON_M4', price = 1000, metadata = { registered = true, serial = 'POL' }, license = 'weapon', grade = 3 },
> 			{ name = 'WEAPON_TASER', price = 500, metadata = { registered = true, serial = 'POL'} },
> 
> 		}, locations = {
> 			vec3(-548.47, -118.25, 37.87)
> 		}, targets = {
> 			{ loc = vec3(-548.47, -118.25, 37.87), length = 0.5, width = 3.0, heading = 270.0, minZ = 30.5, maxZ = 32.0, distance = 6 }
> 		}
> },

Thanks if you can resolve this issue @renzuzu appreciate

**Comment by renzuzu** [comment]
can you confirm which one is not workign, the groups or the grade?

**Comment by killA93i** [comment]
For default shop = groups and grade not working. (not for ownedshop).  I downloaded last version with no any change from me, and with ox_target or simple drawmarker not working too. I use ESX Legacy (no multicharacter) / Ox_inventory (latest) / ox_lib (latest) and ox_target

**Comment by renzuzu** [comment]
please only one by one issue.

is your issue is grade or the marker / target issue?

are you editing defaultshops.lua for groups thing?

you cant do that there.

you need to do that in ownedshops.lua

only ownedshops or non purchase owned shops can have groups

and as for grade. its not implemented yet..
i will push asap about this grade feature.

thanks for creating a feedback and issue.

**Comment by killA93i** [comment]
Hello @renzuzu, my issue is not about marker or target issue. 

I want create basic shop for my job like police, ambulance working well with ox_inventory.
But when i have renzu_shops, i cant add groups for any shops (not buyable). I dont want change anything for buyable store, only want to create basic shop for my job like before. Example: Want to create a simple shop for police, an armory, create my shop not ownable in defaultshops.lua with a groups = 'police'. Everyone on the server can open the shop, the group restriction not working for this shop. 

I don't have ownedshops.lua


Thanks @renzuzu for taking time for resolve all issue.

**Comment by renzuzu** [comment]
this https://github.com/renzuzu/renzu_shops/commit/59b991b6d3f9d0795f54f264e1d6520504db9043 will support job grades..

just do what your doing like ox_inventory.

`{name = 'burger', price = 100, grade = 4}`

**Comment by killA93i** [comment]
All workings good thanks a lot @renzuzu, you delivery a nice support thanks you.
