### ISSUE TITLE
blips

### ISSUE THREAD

**Issue by xJkaay** [renzuzu/renzu_shops#35]
blips dont stay upon joining the server as like script isnt started but is

**Comment by xJkaay** [comment]
Only with movable shops it seems like hotdog stand

**Comment by renzuzu** [comment]
> blips dont stay upon joining the server as like script isnt started but is

can you explain this in detail, hows the blips not staying?

**Comment by xJkaay** [comment]
I figure it all out except the vehicle shop blips the register is there and the place to buy the shop but the blips to buy vehicles wont appear

**Comment by renzuzu** [comment]
>blips to buy vehicles

do you mean markers?
