### ISSUE TITLE
Don't allow items that don't exist (aren't present in the QBShared.Items table) to populate in the shop.

### ISSUE THREAD

**Issue by jellyton69** [renzuzu/renzu_shops#37]
Implement a check to prevent items that don't exist (aren't present in the QBShared.Items table) from populating in the shop.

**Comment by renzuzu** [comment]
im still un decided on this, developers can always remove the missing items.
compare confusing developer that the shop is empty incase of all items is not installed.

**Comment by jellyton69** [comment]
Yeah, I see where you're coming from, I think the best way to get around this is to print out in the console what items don't exist and inform them that they won't be populated in the shop. It's better than having players try to buy an item that doesn't exist. It's better for the developer/server owner to be confused than a player from a UX perspective.

**Comment by Krypt0n93** [comment]
![7D642475-4540-44C1-895F-F1B4E3FA1D43](https://user-images.githubusercontent.com/100892770/214197595-12a85fcc-8e0f-4fda-9b52-62148cc95f4b.png)
So I put this in and this is what I get don’t understand what I did wrong
