### ISSUE TITLE
upgrade stores

### ISSUE THREAD

**Issue by FilipeCuco** [renzuzu/renzu_shops#4]
possibility for the store owner to create custom categories and add the items he wants

**Comment by renzuzu** [comment]
What logic could be?

Its possible but the item should be register in your system

Ex usable items and ox inv data items

**Comment by FilipeCuco** [comment]
basically from the moment someone buys a store, not having pre-set items or categories and adding an option to that menu to "Create new Category" and "Add / Remove Item" / "Set Price" would be very interesting
![image](https://user-images.githubusercontent.com/116587926/201091169-09c32760-eda6-4cb2-bb3f-5d1f411932cd.png)

**Comment by FilipeCuco** [comment]
and another thing you could do to stop people from selling guns in a food store is to add a blacklist of items that cannot be sold in food stores and a whitelist for items that can be sold

**Comment by renzuzu** [comment]
im Already doing this.
![image](https://user-images.githubusercontent.com/82306584/201109766-66dcc5bc-bbd9-4c34-bb14-66db7e78c324.png)

the Add Item button is on the Store items from the category.
so when you add new item its assign to that category

as for adding category its outside functions

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/201110357-e2850984-59f1-45d6-9022-fbafcfc49cbc.png)

**Comment by FilipeCuco** [comment]
another thing you could add for when you own a store is to be able to lock the doors

**Comment by FilipeCuco** [comment]
Are you thinking about putting Fuel stations?

**Comment by Im-Kayun** [comment]
I think you misunderstood Filipe's suggestion. From what Filipe told me, when a player buys a store he can only add to the store the existing items in the config. What he was trying to say was, the stores can have the items (existing in the inventory) and categories that the player wants, not necessarily the config items, but there should be a blacklist and whitelist on the store items so the developers can better control the items inside the RP. In my opinion as a staff of a RP server it makes no sense that store owners can create new items/attributes, and there could be a great abuse.

**Comment by Im-Kayun** [comment]
Yes, can add existing items from data/items.lua

**Comment by renzuzu** [comment]
> Are you thinking about putting Fuel stations?

i wanted to add it, but its going to be overkill for a shop resource, as i already added vehicle since its  a shop type.
and one reason that i did not do it is there will be a dependency of fuel script and the current UI is not fit for Refilling Logic UI like Fuel.

**Comment by Im-Kayun** [comment]
Yes, you are right. Maybe it is better for a future script, because although fuel stations are also a type of store it would overload the script too much
