### ISSUE TITLE
Enhancement (jobs)

### ISSUE THREAD

**Issue by dim62** [renzuzu/renzu_shops#42]
add an option to the owner to be able to setjob in the name of the store in order to use renzu_jobs and create buyable business tell mechanic farms ect

**Comment by renzuzu** [comment]
setjob , you mean the job can access the shop business manage?

its already supported , go to Employee management, you can add job access

**Comment by dim62** [comment]
> setjob , vous voulez dire que le travail peut accéder à la gestion de l'entreprise de la boutique ?
> 
> c'est déjà pris en charge, allez dans Gestion des employés, vous pouvez ajouter un accès à l'emploi

yes I noticed but when I buy a store I am unemployed and when I give access to employment it is unemployed 
example: I am unemployed I buy a store ex bennys or lscustoms to have the possibility to the boss to setjob (bennys boss) so he can use the configuration of renzu_jobs and renzu_customs for example and the players have access to the job bennys + store for the sale of items

idea for the configuration (VehicleShop)
	[1] = {
		groups = 'pdm',
		setjob_owner = 'pdm grade boss',
		 
		moneytype = 'money',
		type = 'vehicle',
		label = 'Premium Deluxe Motorsports',
		coord = vec3(-31.42,-1106.44,26.422),
		purchase = vec4(-31.88,-1091.17,25.74,337.1),
		spawn = vec4(-46.166618347168,-1095.1260986328,25.746654510498,149.61434936523),
		restock = vec4(-49.725978851318,-1077.2698974609,27.09181022644,68.993782043457),
		cashier = vec3(-55.57,-1097.97,26.42),
		blip = {
			id = 402, colour = 69, scale = 0.8
		},
		price = 3000000,
		supplieritem = shared.Storeitems.VehicleShop,
		camerasetting = {offset = vec3(0.0,-1.2,0.0), fov = 25},
		showcase = {
			[1] = {
				coord = vec3(-36.91731262207,-1103.2255859375,26.42), 
				label = 'Spot 1',
				position = vec4(-39.272773742676,-1102.9514160156,25.754877090454,291.85345458984),
			},
			[2] = {
				coord = vec3(-43.74,-1097.87,26.42), 
				label = 'Spot 2',
				position = vec4(-41.56,-1096.429,25.75,131.42),
			},
			[3] = {
				coord = vec3(-47.055,-1096.91,26.42), 
				label = 'Spot 3',
				position = vec4(-49.671222686768,-1098.3825683594,25.754959106445,309.06005859375),
			},
		}
	},

**Comment by renzuzu** [comment]
you can add groups in ownedshops
```

        moneytype = 'money',
	type = 'vehicle',
	label = 'Premium Deluxe Motorsports',
        groups = 'pdm',
	```
	job grades are not supported yet as when you give access to if the shop have groups.
	
	only the owner can access financial, and other things.
