### ISSUE TITLE
Player booth - Not appearing when being used/F8 Error

### ISSUE THREAD

**Issue by lordfalcon22** [renzuzu/renzu_shops#44]
Framework: Qbcore/Qbox
Inventory: Ox_inventory

Replicate: 
Use the "Playerbooth" Item and it will show a progress bar, When finishes it shows the UI but no stall appears.. Following a error in F8 console.

![image](https://user-images.githubusercontent.com/34603343/206327539-6a6bad84-8d0e-4c9e-b8ec-a3a9a639c1f9.png)

**Comment by renzuzu** [comment]
did you just spawn it?
it would not work if you spawn,, the playerbooth uses metadata
