### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by polopokky** [renzuzu/renzu_shops#47]
![adfe](https://user-images.githubusercontent.com/73616076/206778098-5dfd1bbd-c6d0-49ac-a2ea-2cf2c47fd4ca.JPG)

**Comment by renzuzu** [comment]
update you ox

**Comment by polopokky** [comment]
> update you ox
Do you mean ox_inventory or oxmysql or ox_lib?

**Comment by ajmedina** [comment]
Use a renzu fork of ox_inventory 
and update oxlib and oxmysql
OXLIB version      '2.18.0'   I HAVE oxmysql version version '2.5.1'  lastone give me errors
