### ISSUE TITLE
Add vehicle pictures? 

### ISSUE THREAD

**Issue by Kmack710** [renzuzu/renzu_shops#49]
How would you go about adding vehicle pictures?

**Comment by renzuzu** [comment]
add it on ox invetory images 
or
use vImageCreator

**Comment by Kmack710** [comment]
vImageCreator just brings me to this screen and doesnt do anything at all. Ive also tried adding vehicle pictures to ox_inventory with none of them ever showing up in the shop? 
![image](https://user-images.githubusercontent.com/69439573/206960410-49c42940-b873-4fa9-8bd5-3f13ce6d9868.png)

**Comment by Kmack710** [comment]
managed to get vimagecreator working but where would I change in renzu_shops to read those pictures?

**Comment by renzuzu** [comment]
its should read automatic, if vImageCreator is started

you could stop it after it save data from GlobalState.

i actually have update regarding this on JS part. its not reading correctly the data from vImageCreator (only category is showing picture in my issue)

**Comment by Kmack710** [comment]
The pictures dont show up at all cause its pulling from your github file. There is no where that it shows vImageCreator export anywhere at all in shops? 

So really dont understand how its suppose to read it if there is no code at all that tells it to read the vImageCreator?

**Comment by renzuzu** [comment]
its uses GlobalState. are you usning recent version?

**Comment by Kmack710** [comment]
I thought i was but updated and it works now! Thanks a ton :)
