### ISSUE TITLE
Pay now freezes shop ui

### ISSUE THREAD

**Issue by NZBlackKiwi** [renzuzu/renzu_shops#51]
![Capture](https://user-images.githubusercontent.com/25287097/208258250-b42faee0-50a7-437c-847d-0deb994927f8.JPG)
only error i get
when i select item to buy then click pay now the shop ui freezes restart script closes it but screen still blurred and cant move char

**Comment by xJkaay** [comment]
what inventory you using?

**Comment by NZBlackKiwi** [comment]
using ox inventory

**Comment by NZBlackKiwi** [comment]
um just clicking on pay causes the freeze

**Comment by NZBlackKiwi** [comment]
also if i use renzu version of ox_inventory i can open with ox gui and not shop gui

**Comment by renzuzu** [comment]
always start ox_inventory before renzu_shops

**Comment by NZBlackKiwi** [comment]
yer mate it does.. doesnt throw an error either which makes it hard
