### ISSUE TITLE
lj-inventory Support

### ISSUE THREAD

**Issue by SirOMGitsYOU** [renzuzu/renzu_shops#52]
Hey - Could it be possible for you to add lj-inventory support to the shops? This would be a great feature as it is more widely used than the normal qb-inventory on qbcore

**Comment by xmidnite** [comment]
Waiting for this! <3

**Comment by Fakiee** [comment]
100% Would love this!!!!!!!!!

**Comment by renzuzu** [comment]
> Hey - Could it be possible for you to add lj-inventory support to the shops? This would be a great feature as it is more widely used than the normal qb-inventory on qbcore

currently i dont have time to implement this.

you can try, or if someone can do a PR

replicate my functions and exports in my forked qb-inventory to lj inventory. since its probably the same logic derrived from qb-inventory.

the only changed in UI part is showing the metadatas (labels and description)

the only functions used the server part of my forked qb-inventory is the movable shops logic (stash register and put and get)

**Comment by Fakiee** [comment]
> 

Man I wish I knew how, I would do it in a heartbeat. Maybe I shall learn cause Renzu Shops is literally the best shop Script ever. I had to stop using Ox_Inventory because Im on QB-Core and ran into many issues, and QB-Inventory is ehhhh.

**Comment by Fakiee** [comment]
> > Hey - Could it be possible for you to add lj-inventory support to the shops? This would be a great feature as it is more widely used than the normal qb-inventory on qbcore
> 
> currently i dont have time to implement this.
> 
> you can try, or if someone can do a PR
> 
> replicate my functions and exports in my forked qb-inventory to lj inventory. since its probably the same logic derrived from qb-inventory.
> 
> the only changed in UI part is showing the metadatas (labels and description)
> 
> the only functions used the server part of my forked qb-inventory is the movable shops logic (stash register and put and get)

If I use your Fork of QB-Core Inventory would it allow me to use Renzu_Shops?

**Comment by renzuzu** [comment]
currently my forked supports all function of the shop resource.
unfortunately i discovered lj-inventory after i crete forked of qb inv.
i agree lj inventory is nice..when i find some good time to do it, i will try
you could also ask qbcore community to do it.
