### ISSUE TITLE
Black market does not work

### ISSUE THREAD

**Issue by TheFlyBandit** [renzuzu/renzu_shops#55]
When you try to buy stuff at the black market it still asks you if you want to pay cash or bank. No matter which one you select nothing works. Even if you have enough in all your accounts and have enough dirty money. No client or server errors.

**Comment by ajmedina** [comment]
Paste your ox_inventory version for me works perfect.

**Comment by renzuzu** [comment]
this is probably a bug in your version.. i have some few updates regarding this
