### ISSUE TITLE
MySql File Mission

### ISSUE THREAD

**Issue by ItzSimmi** [renzuzu/renzu_shops#56]
I Need the SQL File to use the Script

**Comment by ajmedina** [comment]
You need to open the files inside scripts 
is on https://github.com/renzuzu/renzu_shops/data/item_install.lua  

Not import sql info to your database 
that info is take from ox_inventory items.lua

Take a fork from inventory https://github.com/renzuzu/ox_inventory
and put the info on item_install.lua ox_inventory/data/items.lua 
example:     	['latte'] = {
		label = 'Latte',
		weight = 50
	},
	['hotsauce'] = {
		label = 'Hot Sauce',
		weight = 50
	},   

that code inside   ox_inventory/data/items.lua  its all

remember if you use garage of renzu for key system on inventory you need to add the key and fakeplate.!!! 
Ciao

**Comment by ItzSimmi** [comment]
But i get an error, thats say: table didnt found

**Comment by renzuzu** [comment]
post a error picture for better information

**Comment by urmawsadafty** [comment]
every time i open the built in UI i cant exit it and it wont pick up cash that im holding and cant purchase anything, also the shops that are purchasable dont show up for some reason any ideas ? im not getting any errors with any of this minus the vehicle shop which i am not using anyway.

**Comment by ajmedina** [comment]
> But i get an error, thats say: table didnt found

The items to ox_inventory used on renzu_shops is on LUA FILE not database
This is used for better PERFORMANCE 
put the info on item_install.lua on ox_inventory/data/items.
