### ISSUE TITLE
stuck in UI

### ISSUE THREAD

**Issue by urmawsadafty** [renzuzu/renzu_shops#57]
every time i open the built in UI i cant exit it and it wont pick up cash that im holding and cant purchase anything, also the shops that are purchasable dont show up for some reason any ideas ? im not getting any errors with any of this minus the vehicle shop which i am not using anyway.

also when i install your forked version of ox_inventory it comes up with a few errors regarding building UI for it too so im using vanilla ox_inventory paired with your renzu_shops-1.1.3

any help would be appreciated.

**Comment by giogimic** [comment]
im unable to purchase and cant leave ui
