### ISSUE TITLE
Having issues with script 

### ISSUE THREAD

**Issue by Krypt0n93** [renzuzu/renzu_shops#68]
![30A49F87-48D7-4F14-9ECC-45A4FEDA4618](https://user-images.githubusercontent.com/100892770/214198059-96079936-2ac5-4f0b-98bd-afa014c68a91.png)
So I put this in yesterday and it gave me this error would you be able to tell me what I did wrong?

**Comment by renzuzu** [comment]
you started this resource before ox_inventory?

**Comment by Krypt0n93** [comment]
yes i did

**Comment by Krypt0n93** [comment]
but i also run a qbcore server
