### ISSUE TITLE
delivering to own shop

### ISSUE THREAD

**Issue by mrdeano** [renzuzu/renzu_shops#73]
is there a way to make it so if you order your items and it does not let you deliver your own items to your own shop and it can be a money glitch

order 100 water bottles for $750
deliver them for $30000

**Comment by mrdeano** [comment]
NVM i was able to implement this myself

**Comment by renzuzu** [comment]
how is this money glitch can you explain in detail

**Comment by mrdeano** [comment]
> how is this money glitch can you explain in detail

so if I was to go to my own store and order let's say 100 water bottles for $750 so I spend $750

then I go to do the delivery for the order I just made and after I did the order it will pay my let's say $1000 and I get the water bottles to sell

so I spend $750 and make $250 and get the water bottles to sell
