### ISSUE TITLE
Buying Items Permissions

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [renzuzu/renzu_shops#76]
Do you know if its possible to add an Ace Permissions check to shop items directly for people running ox inventory with this script who are on standalone servers? 

I've seen one script do this where they added it to their items buying code itself which worked great and would not allow someone to buy the item in the shop without the proper Ace permission. But as whole on the shop end of things it might be easier than every single script themselves.

Useful for weapons as well as many servers are using these perms synced with Discord roles.

**Comment by renzuzu** [comment]
why not just remove the weapon on equiped if player dont have permission to use?

i will try to look if your suggested logic is possible in client side
so player wont see the item in shop if dont have permission
