### ISSUE TITLE
Cars is not yours

### ISSUE THREAD

**Issue by QBCoreStore** [renzuzu/renzu_shops#77]
When I purchase Cars From Renzu Shops ( Vehicle Shop) it shows Cars is not yours. 

I use qb-vehiclekeys

How Can I fix it?

**Comment by Fakiee** [comment]
I have the same problem, but it still lets me store it in the garage just when it spawns it doesn't give me the keys. I have to store it first

**Comment by renzuzu** [comment]
this is probably , your using incorrect event in the config, to give proper keys

**Comment by QBCoreStore** [comment]
> this is probably , your using incorrect event in the config, to give proper keys

Can you tell me how can we fix it?

**Comment by renzuzu** [comment]
what is your qbcore event?

**Comment by QBCoreStore** [comment]
local QBCore = exports['qb-core']:GetCoreObject()

**Comment by renzuzu** [comment]
no the event to give vehicle keys

**Comment by QBCoreStore** [comment]
> no the event to give vehicle keys

https://github.com/qbcore-framework/qb-vehiclekeys I am using default QB-Vehiclekeys

**Comment by QBCoreStore** [comment]
> no the event to give vehicle keys

Please Help

**Comment by renzuzu** [comment]
the default in config.
```
TriggerClientEvent('vehiclekeys:client:SetOwner', source, plate)
```

are still existed in the qb keys repo.

show me the config

the default in this resource support qb core keys

you need to setup this config
```
shared.VehicleKeysType = {
	['export'] = false, -- if false it will use trigger events
	['client'] = true, -- if false it will use server event or server exports
}
```

**Comment by QBCoreStore** [comment]
> the default in config.
> 
> ```
> TriggerClientEvent('vehiclekeys:client:SetOwner', source, plate)
> ```
> 
> are still existed in the qb keys repo.
> 
> show me the config
> 
> the default in this resource support qb core keys
> 
> you need to setup this config
> 
> ```
> shared.VehicleKeysType = {
> 	['export'] = false, -- if false it will use trigger events
> 	['client'] = true, -- if false it will use server event or server exports
> }
> ```

I tried that But After this, I can't even see the BLIP. No blip for buy cars
