### ISSUE TITLE
Vault not adding money

### ISSUE THREAD

**Issue by Fakiee** [renzuzu/renzu_shops#78]
I recently added renzu_shops and have been testing each feature slowly, I just started testing the buyable shops function, when I try and add funds to the vault, it says they are added, but nothing actually goes in the vault. I am on QB-Core and I recently switched to PEFCL for Banking (https://github.com/project-error/pefcl) I have 100 Mil in Cash and Bank, so its not that

**Comment by renzuzu** [comment]
why your mentioning banking resource, its does not have to do with bank.

the vault money is on the store owner menu 
-> finance management

**Comment by Fakiee** [comment]
> why your mentioning banking resource, its does not have to do with bank.
> 
> the vault money is on the store owner menu 
> -> finance management

I wasn't sure if it was because its not working with the bank. Any thoughts what it could be?

**Comment by Fakiee** [comment]
Ok So I just got on and after a server restart its working now
