### ISSUE TITLE
Store employees

### ISSUE THREAD

**Issue by lordfalcon22** [renzuzu/renzu_shops#79]
When purchasing a shop. You request a friend to be a employee for the shop. They accept but when they try to use the store menu it fires them. I checked the sql as well to see if it was inserting them but it isn't.

Simple terms: Unable to recruit another player into the store.

**Comment by renzuzu** [comment]
afaik the recruitment need s relogin of player 
new player loaded event.

**Comment by lordfalcon22** [comment]
Yeah I tried that. Steps I did:

1. Hire a player
2. They leave the server and rejoin
3. They try to access menu
4. They get fired instantly and nothing is entered into the database
