### ISSUE TITLE
qb-target Support

### ISSUE THREAD

**Issue by mozuki345** [renzuzu/renzu_shops#81]
qb-target Support :)

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_shops/blob/99eee862b41e7458403fdb0cb0b72a211b9532c1/client/main.lua#L96

just replace qtarget to qb-target.

**Comment by mozuki345** [comment]
tried does not work ^^

**Comment by renzuzu** [comment]
> does not work

put more info, does error thow? try exports['qb-target']

**Comment by mozuki345** [comment]
I would give you more info if I had any :D

if I replace only qb-target an error message appears but if I use ['qb-target'] no error message appears but if I want to work with qb-target nothing happens 

> > does not work
> 
> put more info, does error throw? try exports['qb-target']

**Comment by renzuzu** [comment]
qb-target should be already supported
