### ISSUE TITLE
QB | Cash issue

### ISSUE THREAD

**Issue by mozuki345** [renzuzu/renzu_shops#82]
Hello,

I noticed that you cant pay with cash. When I use a shop, I also see that it says Cash 0$ at the top.

**Comment by mozuki345** [comment]
small addition;

If you change the following in client/main.lua and server/main.lua, the cash is displayed correctly in qb.

FROM 
self.GetAccounts('money')

TO
from self.GetAccounts('cash')


I think a query would be helpful here where exactly I still have to find out

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_shops/commit/0eb00f7be0a51aece3615bcaf6bc1151a9f4c30a
