### ISSUE TITLE
qb-weapons issue

### ISSUE THREAD

**Issue by mozuki345** [renzuzu/renzu_shops#83]
SCRIPT ERROR: @renzu_shops/init.lua:126: No such export getConfigWeaponAttachments in resource qb-weapons

I already know why the error is coming, Im just posting it for the record.

**Comment by renzuzu** [comment]
update your qb-weapons

**Comment by mozuki345** [comment]
> update your qb-weapons

Is it current, or do you have a modified form of it?

**Comment by renzuzu** [comment]
Qb weapons should have export for that.

Unless your starting it after this resource
