### ISSUE TITLE
issue collection

### ISSUE THREAD

**Issue by mozuki345** [renzuzu/renzu_shops#84]
Hey, 

I have now tested renzu_shops a bit and I'll write here what I noticed that doesn't work yet.

**Every time I start or restart the script I get a warning (client-side):**

> Warning: command 'addstockall' is using deprecated syntax for lib.addCommand
> update the command or use lib.__addCommand to ignore this warning
> renzu_shops/server/main.lua^0:352)^7
> command 'storeadmin' is using deprecated syntax for lib.addCommand
> update the command or use lib.__addCommand to ignore this warning
> @renzu_shops/server/main.lua^0:393)^7

**When I want to create a shop with /storeadmin I get this error message (server-side):**
```
[  script:renzu_shops] SCRIPT ERROR: @renzu_shops/server/main.lua:444: attempt to index a nil value (field 'integer index')
[  script:renzu_shops] > callbackResponse (@ox_lib/callback/server.lua:60)
[  script:renzu_shops] > handler (@ox_lib/callback/server.lua:76)
```

The display of how much is still in stock in the shop is somehow not updated.
Example: 100 water standard in it I buy 50 is still infinite in it. When I go to manage the shop, I see that there are only 50 left.

as soon as I notice more I will give feedback :)

**Comment by renzuzu** [comment]
the ox lib warning is fixed, i updated the resource to use new command syntax for v3.

as for the other error , you should re try again.

if using qbcore create a shop using zones. as this is the only tested method when creating shop.
