### ISSUE TITLE
Cannot Put Delivery box on vehicle

### ISSUE THREAD

**Issue by fazitanvir** [renzuzu/renzu_shops#85]
![Screenshot_3](https://user-images.githubusercontent.com/70646347/225583067-b4433470-07b8-49ff-a044-49e069f3adc2.jpg)

Cannot put delivery box to delivery vehicle, Draw Marker doesn't appear and after pressed [E] nothing happen

**Comment by renzuzu** [comment]
my tests works fine with the latest main branch.

**Comment by nathan-collab** [comment]
I had the same problem when I changed vehicle, I advise you to keep as the basic vehicle so the mule
