### ISSUE TITLE
moneytype different currency/item UI issue

### ISSUE THREAD

**Issue by Jonneis** [renzuzu/renzu_shops#86]
Is better to add the currency icon plus the amount otherwise is undefined

[Pic](https://i.gyazo.com/efb17f4dd8cbc75f0b09efeefe894f69.png)

**Comment by renzuzu** [comment]
![image](https://user-images.githubusercontent.com/82306584/229298563-b35f2ab8-409a-430a-9648-c984094f4ab1.png)

better late than never.

tested currently on ox_inventory

**Comment by Jonneis** [comment]
How does it work though, coz maybe u want to buy specific items that cost different currecy for example

![pr](https://user-images.githubusercontent.com/32698908/229320068-245942e7-07c2-4ba8-826f-f644946b3541.png)

**Comment by renzuzu** [comment]
the currency setting is per shop
