### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by Kingsman40** [renzuzu/renzu_shops#87]
Hey renzu,

I am getting this long error. 

[  script:renzu_shops] SCRIPT ERROR: [string "local dbdata = {['financedata'] = {['columns'..."]:201: bad argument #1 to 'for iterator' (table expected, got nil)
[  script:renzu_shops] > [global chunk] (ocal dbdata = {['financedata'] = {['columns'] = '`identifier`,`max`,`financed`',['values'] = '?,?,?'},['renzu_stores'] = {['columns'] = '`shop`,`owner`,`money`,`items`,`employee`,`cashier`,`customitems`,`job`',['values'] = '?,?,?,?,?,?,?,?'},['movableshops'] = {['columns'] = '`identifier`,`owner`,`money`,`items`,`plate`,`type`,`shopname`',['values'] = '?,?,?,?,?,?,?'},}
[  script:renzu_shops] 
[  script:renzu_shops] local db = setmetatable({},{
[  script:renzu_shops] 	__call = function(self)
[  script:renzu_shops] 
[  script:renzu_shops] 		self.insert = function(name, data)
[  script:renzu_shops] 			local str = 'INSERT INTO %s (%s) VALUES(%s)'
[  script:renzu_shops] 			return MySQL.insert.await(str:format(name,dbdata[name].columns,dbdata[name].values),data)
[  script:renzu_shops] 		end
[  script:renzu_shops] 
[  script:renzu_shops] 		self.update = function(name, column, where, update, data)
[  script:renzu_shops] 			local str = 'UPDATE %s SET %s = ? WHERE %s = ?'
[  script:renzu_shops] 			return MySQL.query(str:format(name,column,where),{data,update})
[  script:renzu_shops] 		end
[  script:renzu_shops] 
[  script:renzu_shops] 		self.delete = function(name, where, update)
[  script:renzu_shops] 			local str = 'DELETE FROM %s WHERE %s = ?'
[  script:renzu_shops] 			return MySQL.query(str:format(name,where),{update})
[  script:renzu_shops] 		end
[  script:renzu_shops] 
[  script:renzu_shops] 		self.save = function(data)
[  script:renzu_shops] 			Citizen.CreateThreadNow(function()
[  script:renzu_shops] 				for shopname,v in pairs(data) do
[  script:renzu_shops] 					local select = MySQL.query.await('SELECT * FROM `renzu_stores` WHERE `shop` = ?', {shopname})
[  script:renzu_shops] 					if select then
[  script:renzu_shops] 						for k,v in pairs(v) do
[  script:renzu_shops] 							if type(v) == 'table' then
[  script:renzu_shops] 								self.update('renzu_stores',k,'shop',shopname,json.encode(v))
[  script:renzu_shops] 							else
[  script:renzu_shops] 								self.update('renzu_stores',k,'shop',shopname,v)
[  script:renzu_shops] 							end
[  script:renzu_shops] 						end
[  script:renzu_shops] 					else
[  script:renzu_shops] 						self.insert('renzu_stores',{
[  script:renzu_shops] 							shopname,
[  script:renzu_shops] 							v.owner,
[  script:renzu_shops] 							json.encode(v['money'] or {}),
[  script:renzu_shops] 							json.encode(v['items'] or {}),
[  script:renzu_shops] 							json.encode(v['employee'] or {}),
[  script:renzu_shops] 							json.encode(v['cashier'] or {}),
[  script:renzu_shops] 							json.encode(v['customitems'] or {}),
[  script:renzu_shops] 							v['job'],
[  script:renzu_shops] 						})
[  script:renzu_shops] 					end
[  script:renzu_shops] 				end
[  script:renzu_shops] 			end)
[  script:renzu_shops] 		end
[  script:renzu_shops] 		return self
[  script:renzu_shops] 	end
[  script:renzu_shops] })
[  script:renzu_shops] local Sql = db()
[  script:renzu_shops] 
[  script:renzu_shops] local success, result = pcall(MySQL.scalar.await, 'SELECT 1 FROM renzu_stores')
[  script:renzu_shops] 
[  script:renzu_shops] if not success then
[  script:renzu_shops] 	MySQL.query([[CREATE TABLE `renzu_stores` (
[  script:renzu_shops] 		`id` int NOT NULL AUTO_INCREMENT KEY,
[  script:renzu_shops] 		`shop` varchar(60) DEFAULT NULL,
[  script:renzu_shops] 		`owner` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		`money` longtext DEFAULT NULL,
[  script:renzu_shops] 		`items` longtext DEFAULT NULL,
[  script:renzu_shops] 		`employee` longtext DEFAULT NULL,
[  script:renzu_shops] 		`cashier` longtext DEFAULT NULL,
[  script:renzu_shops] 		`customitems` longtext DEFAULT NULL,
[  script:renzu_shops] 		`job` varchar(64) DEFAULT NULL
[  script:renzu_shops] 	)]])
[  script:renzu_shops] end
[  script:renzu_shops] local success, result = pcall(MySQL.scalar.await, 'SELECT 1 FROM movableshops')
[  script:renzu_shops] 
[  script:renzu_shops] if not success then
[  script:renzu_shops] 	MySQL.query([[CREATE TABLE `movableshops` (
[  script:renzu_shops] 		`identifier` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		`owner` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		`money` longtext DEFAULT NULL,
[  script:renzu_shops] 		`items` longtext DEFAULT NULL,
[  script:renzu_shops] 		`plate` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		`type` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		`shopname` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		UNIQUE KEY `identifier` (`identifier`)
[  script:renzu_shops] 	)]])
[  script:renzu_shops] end
[  script:renzu_shops] 
[  script:renzu_shops] local success, result = pcall(MySQL.scalar.await, 'SELECT 1 FROM financedata')
[  script:renzu_shops] 
[  script:renzu_shops] if not success then
[  script:renzu_shops] 	MySQL.query([[CREATE TABLE `financedata` (
[  script:renzu_shops] 		`identifier` varchar(64) DEFAULT NULL,
[  script:renzu_shops] 		`max` INT(64) DEFAULT NULL,
[  script:renzu_shops] 		`financed` longtext DEFAULT NULL,
[  script:renzu_shops] 		UNIQUE KEY `identifier` (`identifier`)
[  script:renzu_shops] 	)]])
[  script:renzu_shops] end
[  script:renzu_shops] 
[  script:renzu_shops] local success, result = pcall(MySQL.scalar.await, 'ALTER TABLE `movableshops` MODIFY COLUMN `identifier` VARCHAR(100)')
[  script:renzu_shops] 
[  script:renzu_shops] local convert = function()
[  script:renzu_shops] 	if GetResourceKvpString('renzu_stores') then
[  script:renzu_shops] 		for k,v in pairs(json.decode(GetResourceKvpString('renzu_stores'))) do
[  script:renzu_shops] 			local columns = {}
[  script:renzu_shops] 			columns['shop'] = k
[  script:renzu_shops] 			local data = {}
[  script:renzu_shops] 			for k,v in pairs(v) do
[  script:renzu_shops] 				columns[k] = v
[  script:renzu_shops] 			end
[  script:renzu_shops] 			Sql.insert('renzu_stores',{
[  script:renzu_shops] 				columns['shop'],
[  script:renzu_shops] 				columns['owner'],
[  script:renzu_shops] 				json.encode(columns['money'] or {}),
[  script:renzu_shops] 				json.encode(columns['items'] or {}),
[  script:renzu_shops] 				json.encode(columns['employee'] or {}),
[  script:renzu_shops] 				json.encode(columns['cashier'] or {}),
[  script:renzu_shops] 				json.encode(columns['customitems'] or {}),
[  script:renzu_shops] 				columns['job'],
[  script:renzu_shops] 			})
[  script:renzu_shops] 		end
[  script:renzu_shops] 	end
[  script:renzu_shops] 
[  script:renzu_shops] 	if GetResourceKvpString('movableshops') then
[  script:renzu_shops] 		for k,v in pairs(json.decode(GetResourceKvpString('movableshops'))) do
[  script:renzu_shops] 			local columns = {}
[  script:renzu_shops] 			columns['shopidentifier'] = k
[  script:renzu_shops] 			local data = {}
[  script:renzu_shops] 			for k,v in pairs(v) do
[  script:renzu_shops] 				columns[k] = v
[  script:renzu_shops] 			end
[  script:renzu_shops] 			Sql.insert('movableshops',{
[  script:renzu_shops] 				columns['shopidentifier'],
[  script:renzu_shops] 				columns['identifier'],
[  script:renzu_shops] 				json.encode(columns['money'] or {}),
[  script:renzu_shops] 				json.encode(columns['items'] or {}),
[  script:renzu_shops] 				columns['plate'],
[  script:renzu_shops] 				columns['type'],
[  script:renzu_shops] 				columns['shopname'],
[  script:renzu_shops] 			})
[  script:renzu_shops] 		end
[  script:renzu_shops] 	end
[  script:renzu_shops] 	if GetResourceKvpString('financedata') then
[  script:renzu_shops] 		for k,v in pairs(json.decode(GetResourceKvpString('financedata'))) do
[  script:renzu_shops] 			local columns = {}
[  script:renzu_shops] 			columns['identifier'] = k
[  script:renzu_shops] 			local data = {}
[  script:renzu_shops] 			for k,v in pairs(v) do
[  script:renzu_shops] 				columns[k] = v
[  script:renzu_shops] 			end
[  script:renzu_shops] 			Sql.insert('financedata',{
[  script:renzu_shops] 				columns['identifier'],
[  script:renzu_shops] 				tonumber(columns['max']),
[  script:renzu_shops] 				json.encode(columns['financed'] or {}),
[  script:renzu_shops] 			})
[  script:renzu_shops] 		end
[  script:renzu_shops] 	end
[  script:renzu_shops] end
[  script:renzu_shops] --DeleteResourceKvp('renzu_stores_convert')
[  script:renzu_shops] if not GetResourceKvpString('renzu_stores_convert') then
[  script:renzu_shops] 	convert()
[  script:renzu_shops] 	SetResourceKvp('renzu_stores_convert', 'true')
[  script:renzu_shops] end
[  script:renzu_shops] 
[  script:renzu_shops] local Stores = {}
[  script:renzu_shops] for k,v in pairs(MySQL.query.await('SELECT * FROM renzu_stores', {  }) or {}) do
[  script:renzu_shops] 	Stores[v.shop] = {}
[  script:renzu_shops] 	for column,data in pairs(v) do
[  script:renzu_shops] 		if string.find(data, '{') then
[  script:renzu_shops] 			Stores[v.shop][column] = json.decode(data)
[  script:renzu_shops] 		elseif data == '[]' then
[  script:renzu_shops] 			Stores[v.shop][column] = {}
[  script:renzu_shops] 		else
[  script:renzu_shops] 			Stores[v.shop][column] = data
[  script:renzu_shops] 		end
[  script:renzu_shops] 	end
[  script:renzu_shops] end
[  script:renzu_shops] 
[  script:renzu_shops] local Movable = {}
[  script:renzu_shops] for k,v in pairs(MySQL.query.await('SELECT * FROM movableshops', {  }) or {}) do
[  script:renzu_shops] 	Movable[v.identifier] = {}
[  script:renzu_shops] 	for column,data in pairs(v) do
[  script:renzu_shops] 		if string.find(data, '{') then
[  script:renzu_shops] 			Movable[v.identifier][column] = json.decode(data)
[  script:renzu_shops] 		elseif data == '[]' then
[  script:renzu_shops] 			Movable[v.identifier][column] = {}
[  script:renzu_shops] 		else
[  script:renzu_shops] 			Movable[v.identifier][column] = data
[  script:renzu_shops] 		end
[  script:renzu_shops] 	end
[  script:renzu_shops] end
[  script:renzu_shops] 
[  script:renzu_shops] local Financed = {}
[  script:renzu_shops] for k,v in pairs(MySQL.query.await('SELECT * FROM financedata', {  }) or {}) do
[  script:renzu_shops] 	Financed[v.identifier] = {}
[  script:renzu_shops] 	for column,data in pairs(v) do
[  script:renzu_shops] 		if string.find(data, '{') then
[  script:renzu_shops] 			Financed[v.identifier][column] = json.decode(data)
[  script:renzu_shops] 		elseif data == '[]' then
[  script:renzu_shops] 			Financed[v.identifier][column] = {}
[  script:renzu_shops] 		else
[  script:renzu_shops] 			Financed[v.identifier][column] = data
[  script:renzu_shops] 		end
[  script:renzu_shops] 	end
[  script:renzu_shops] end
[  script:renzu_shops] 
[  script:renzu_shops] for k,v in pairs(shared.OwnedShops) do
[  script:renzu_shops] 	local str = 'Stores_%s'
[  script:renzu_shops] 	for k,v in pairs(v) do
[  script:renzu_shops] 		GlobalState[str:format(v.label)] = nil
[  script:renzu_shops] 	end
[  script:renzu_shops] end
[  script:renzu_shops] AddStateBagChangeHandler("Stores", "global", function(bagName, key, value)
[  script:renzu_shops] 	Wait(0)
[  script:renzu_shops] 	if not value then return end
[  script:renzu_shops] 	for shop,data in pairs(value) do -- Split datas to dedicated bags to prevent byte size limits
[  script:renzu_shops] 		local str = 'Stores_%s'
[  script:renzu_shops] 		GlobalState[str:format(shop)] = data
[  script:renzu_shops] 	end
[  script:renzu_shops] end)
[  script:renzu_shops] 
[  script:renzu_shops] GlobalState.Shipping = json.decode(GetResourceKvpString('shippingcompany') or '[]') or {}
[  script:renzu_shops] GlobalState.Stores = Stores
[  script:renzu_shops] GlobalState.MovableShops = Movable
[  script:renzu_shops] GlobalState.FinanceData = Financed
[  script:renzu_shops] GlobalState.JobShop = {}
[  script:renzu_shops] return Sql:201)
[  script:renzu_shops] > fn (@renzu_shops/server/main.lua:41)
[  script:renzu_shops] > <unknown> (@oxmysql/dist/build.js:22252)
[  script:renzu_shops] > processTicksAndRejections (node:internal/process/task_queues:96)

But as seen in this screenshot, the tables and columns have been created
https://i.postimg.cc/02HCHQrx/renzu-shops-db-error.png

Any ideas? Thanks.

**Comment by Kingsman40** [comment]
Found the issue
Line 210 for shop,data in pairs(value) do

You have a comma in shop,data. I believe it should be shop.data. Correct?

**Comment by renzuzu** [comment]
when does this error throwing?

>You have a comma in shop,data. I believe it should be shop.data. Correct?

shop is the index name and data is the value.

do you have producable steps how to perform with error?

**Comment by Kingsman40** [comment]
The error thows upon server restart. Watching the live console.

when I added the period in shop.data, the error went away. But now I get error in new issue posted.

**Comment by renzuzu** [comment]
oh, this is known issue when you restart the server via txadmin.

**Comment by renzuzu** [comment]
>when I added the period in shop.data, the error went away. But now I get error in new issue posted.

when you do this , the next boost up will probably have problems in client side

**Comment by Kingsman40** [comment]
Well, the error comes back if I put the comma back in. So it can be ignored?

**Comment by Kingsman40** [comment]
Yeah it's not working with that Database error. Something needs to get fixed. I deleted entire folder, then re-add it back in only changing Framework and inventory lines. Was able to open menu, but after finishing setup of store, I go to Manager Store and there is nothing there. It doesn't seem to be inputting it to the database.

**Comment by renzuzu** [comment]
i will retry in qbcore, hold one.
in esx there is not issue even dropping the table and recreating automatically from resource

**Comment by renzuzu** [comment]
i just tried default qbcore , qb-inventory
there is no issue with database.

the error when shutdowning is you can ignore for now

**Comment by Kingsman40** [comment]
I just tried the 1.2.1 version, still get the same error. Even tried deleting the tables in the database (renzu_stores, moveablestores and financedata) and restarted server. Still same error. This sucks because I really like the look of your script and really wanted to use it. But I guess I'll have to get a paid one that works similar to yours as all the other free one's don't have your features.

Thanks for trying to help. Wish I could figure out the issue.

**Comment by Kingsman40** [comment]
This is the error when starting the server. It does it every time. 

In order from error1 to error6.

https://i.postimg.cc/y8W4Rk3Z/renzushops-error1.png
https://i.postimg.cc/KjNSPT5n/renzushop-error2.png
https://i.postimg.cc/jdMYCz2T/renzushops-error3.png
https://i.postimg.cc/kXJdnjnw/renzushops-error4.png
https://i.postimg.cc/gcqWb9Pn/renzushops-error5.png
https://i.postimg.cc/sxyCGm5j/renzushops-error6.png

Yes I have your qb-inventory.
I have ox_lib (it's in the [standalone] folder by qbcore default)
the name of the folder is renzu_shops
And OneSync is on.

**Comment by Kingsman40** [comment]
Okay, just tried your 1.2.2 version. No error anymore, but the Create Store info is not passing to the database. It has created the database tables, but for some reason, after setting the points and clicking on Create Store, it says Successful but nothing in the database.

**Comment by Kingsman40** [comment]
Ok i found an error on 1.2.2

SCRIPT ERROR: [string "local self = {}..."]:96: attempt to perform arithmetic on a nil value (local 'coord')

**Comment by renzuzu** [comment]
i tried, its seems the 8Balls in config producing the error when lua is re created. with 8Balls instead of ['8Balls']

in the latest branch i renamed it, and it should not mess up the defaultshops.lua anymore

**Comment by Kingsman40** [comment]
Well, i hate to be the bearer of bad news, but still getting errors. 
https://i.postimg.cc/LshrhT8P/renzu-shops-anothererror.png

**Comment by Kingsman40** [comment]
Ok, for some reason, I downloaded the new files, but 8balls wasn't changed. I changed it and that error went away.

But, getting error "Failed to load @renzu_shield/init.lua   What is renzu_shield? I see it in the fxmanifest "shared_script '@renzu_shield/init.lua'"

**Comment by Kingsman40** [comment]
And I told you about this error before, but you haven't seemed to have fixed it

SCRIPT ERROR: [string "local self = {}..."]:96: attempt to perform arithmetic on a nil value (local 'coord')

**Comment by Kingsman40** [comment]
> resource saves only to database when someone buy the store

Ah okay, thanks. 

> create a shop using target disable , as i tested this with zones enable.
> i will try to fix the issue when creating a shop with target enable later..

Disabling target worked. I can now create stores, but yes I think it would be better when you get target working.
