### ISSUE TITLE
Attempt to call a nil value error

### ISSUE THREAD

**Issue by Kingsman40** [renzuzu/renzu_shops#88]
Line 97 to 102 in init.lua

function request(file)
	local name = ('%s.lua'):format(file)
	local content = LoadResourceFile(GetCurrentResourceName(),name)
	local f, err = load(content)
	return f()
end

[  script:renzu_shops] SCRIPT ERROR: @renzu_shops/init.lua:101: attempt to call a nil value (local 'f')
[  script:renzu_shops] > request (@renzu_shops/init.lua:101)
[  script:renzu_shops] > fn (@renzu_shops/server/main.lua:41)

**Comment by renzuzu** [comment]
did you add or modify some file?

the error will throw only if there is some syntax error in some lua files or if file is not existed (mostly from ownedshop)

**Comment by Kingsman40** [comment]
Nothing. I put the folder "renzu_shops" in resources. The only 2 things I changed was 

shared.framework = 'QBCORE' -- ESX || QBCORE
shared.inventory = 'qb-inventory' -- 'ox_inventory' or 'qb-inventory' https://github.com/renzuzu/qb-inventory

And using your forked qb-inventory.

**Comment by Kingsman40** [comment]
Also get this error when restarting server

[  script:renzu_shops] SCRIPT ERROR: @renzu_shops/server/main.lua:1887: attempt to call a nil value (field 'save')
[  script:renzu_shops] > handler (@renzu_shops/server/main.lua:1887)
[  script:renzu_shops] > ref (@monitor/resource/sv_main.lua:243)

I haven't touched any other files.

**Comment by renzuzu** [comment]
this is probably related to some topics i read in forums.

when server is restarting, most of threads gets destroyed or unable to create new threads at all.

i will try to find another way to work around on this.

while this is not really a lethal error, every shop data is saved if its data is changed. eg. new stocks, someone buys, etc.
