### ISSUE TITLE
Runtime Shop Loading

### ISSUE THREAD

**Issue by chaze117** [renzuzu/renzu_shops#89]
Hi!
It is possible to load shops at runtime? 
I mean when I register a shop with exports.ox_inventory:RegisterShop and try to open it with exports.ox_inventory:openInventory I get an error. I attached the log if it helps.
[CitizenFX_log_2023-03-20T202534.log](https://github.com/renzuzu/renzu_shops/files/11022870/CitizenFX_log_2023-03-20T202534.log)

**Comment by renzuzu** [comment]
i think this is ox_inventory your asking,.

if i understand correctly your question.

you cannot register using manual registerShop using OX. and run it on renzu_shops
this resource have standalone logic of handling CreatedShop from storeadmin command.

and any Shop config from ox_inventory is overrided.

**Comment by chaze117** [comment]
So first of all I used an older version of your script when the error occured. In the latest version no error and the shop opens in ox_inventory UI which is half of what I try to do. I don't know why won't your script override this created shop. 
I try to avoid to put things like this in other scripts config files because when the script updated I overwritre my modified configs. I know this is my mistake.
The builtin create shop command is not usable in this case because I want to make a custom shop and the command is for 3 preconfigured shops.
But if it not possible I am happy with the current state.

**Comment by renzuzu** [comment]
>It has any effect other than opening default ox_inventory shops when I set to qb-inventory?

no qb shop is standalone resource, you need to stop the resource or remove the config with the same coordinates like. general store etc..
