### ISSUE TITLE
taco van bug

### ISSUE THREAD

**Issue by KuroScripts** [renzuzu/renzu_shops#9]
when in the taco van when you press move cart/stop selling the camera gets stuck

**Comment by renzuzu** [comment]
you can press E again. to return the menu
i havent maked the taco user friendly yet

**Comment by KuroScripts** [comment]
E doesn’t work

**Comment by renzuzu** [comment]
are you refering the camera setting?

the camera setting on taco van is stuck with higher view.

because your ped is attached in vehicle.
i will try to redo the camera setting of taco. maybe a setting that you can move camera

if your menu wont show when you press E thats a problem. let me know.
