### ISSUE TITLE
do you have a discord 

### ISSUE THREAD

**Issue by Peez500** [renzuzu/renzu_shops#99]
need a discord for support have errors

**Comment by renzuzu** [comment]
your here why you dont post information about your problem?

**Comment by Peez500** [comment]
![image](https://user-images.githubusercontent.com/121979322/229322447-900191e1-79d2-48b3-bbb9-f0c3b0e26b7b.png)
this lil error

**Comment by Peez500** [comment]
can u help

**Comment by renzuzu** [comment]
where does this error came from?

i tried checking the lines it does not match the current update from main branch, so i cannot guess
